
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: packid
  username: postgres
  password: postgres
test:
  <<: *default
  database: packid
  username: postgres
  password: postgres

production:
  <<: *default
  database: packid
  username: postgres
  password: postgres
